@localUrl = http://localhost:3000/

### Gets all Stores
GET {{localUrl}}stores

### Creates one store
POST {{localUrl}}stores HTTP/1.1
Content-Type: application/json

{
    "store_id": "test",
    "store_name": "test name",
    "vehicle_inventory": [],
    "parts_inventory": []
}

### Gets one store
GET {{localUrl}}stores/test

### Updates one store
PUT {{localUrl}}stores/test HTTP/1.1
Content-Type: application/json

{
    "store_id": "test",
    "store_name": "updated test name",
    "vehicle_inventory": [],
    "parts_inventory": []
}

### Deletes one store
DELETE {{localUrl}}stores/test