### Gets all Stores
GET http://localhost:3000/stores

### login
GET http://localhost:3000/login

### Creates one store
POST http://localhost:3000/stores HTTP/1.1
Content-Type: application/json

{
    "store_id": "test",
    "store_name": "test name",
    "vehicle_inventory": [],
    "parts_inventory": []
}

### Gets one store
GET http://localhost:3000/stores/test

### Updates one store
PUT http://localhost:3000/stores/test HTTP/1.1
Content-Type: application/json

{
    "store_id": "test",
    "store_name": "updated test name",
    "vehicle_inventory": [],
    "parts_inventory": []
}

### Deletes one store
DELETE http://localhost:3000/stores/test